name: Daily Commit

on:
  schedule:
    - cron: '5 3 * * *'  # Runs every day at 03:05 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add daily commit by 23f2002758@ds.study.iitm.ac.in
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Commit made on $(date)" >> daily-log.txt
          git config --global user.name "EduDocs Bot"
          git config --global user.email "23f2002758@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily commit: $(date)" || echo "Nothing to commit"
          git push "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}" HEAD:main
